# Only used for local development and setup for unittests

version: "3"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:15.1.1
    ports:
      - "35789:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    depends_on:
      - postgres
    security_opt:
      - no-new-privileges:true

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    security_opt:
      - no-new-privileges:true

volumes:
  postgres_data:
    driver: local
