frameworkVersion: ">=2.71.0 <3.0.0"

service: okdata-permission-api

provider:
  name: aws
  runtime: python3.9
  memorySize: 1024
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${self:custom.deploymentBucket.${self:provider.stage}, self:custom.deploymentBucket.dev}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  rolePermissionsBoundary: "arn:aws:iam::${aws:accountId}:policy/oslokommune/oslokommune-boundary"
  iamManagedPolicies:
    - "arn:aws:iam::${aws:accountId}:policy/okdata-permission-api"
    - "arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess"
  tags:
    GIT_REV: ${git:branch}:${git:sha1}
    VERSION: ${self:custom.version}
  environment:
    GIT_REV: ${git:branch}:${git:sha1}
    STAGE: ${self:provider.stage}
    VERSION: ${self:custom.version}
    SERVICE_NAME: ${self:service}
    KEYCLOAK_REALM: api-catalog
    KEYCLOAK_SERVER: ${ssm:/dataplatform/shared/keycloak-server-url}
    CLIENT_ID: okdata-permission-api
    RESOURCE_SERVER_CLIENT_ID: okdata-resource-server
    ROOT_PATH: "/okdata-permission-api"
    LOG_LEVEL: INFO
    BACKUP_BUCKET_NAME: ${self:custom.backupBucket.${self:provider.stage}, self:custom.backupBucket.dev}
package:
  exclude:
    - '**/*'
  include:
    - dataplatform_keycloak/*.py
    - models/*.py
    - resources/*.py
    - backup/*.py
    - webhook_tokens/*.py
    - app.py
    - handler.py

functions:
  app:
    handler: handler.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
    timeout: 29
  backup:
    handler: backup.handler.backup_permissions
    events:
      - schedule: cron(0 0 * * ? *)
    timeout: 30

plugins:
  - serverless-python-requirements
  - serverless-plugin-git-variables
  - serverless-es-logs

resources:
  Description: |
    ${self:service} ${git:branch}:${git:sha1}
    ${git:message}

custom:
  version: 0.1.0
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    usePoetry: false
  esLogs:
    endpoint: ${ssm:/dataplatform/shared/logs-elasticsearch-endpoint}
    index: dataplatform-services
    filterPattern: '{ $.function_name = "*" }'
  exportGitVariables: false
  deploymentBucket:
    prod: ok-origo-dataplatform-config-prod
    dev: ok-origo-dataplatform-config-dev
  backupBucket:
    prod: ok-origo-dataplatform-backup-prod
    dev: ok-origo-dataplatform-backup-dev
