frameworkVersion: ">=2.10.0 <3.0.0"

service: policy-server-poc

provider:
  name: aws
  runtime: python3.7
  memorySize: 1024
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${self:custom.deploymentBucket.${self:provider.stage}, self:custom.deploymentBucket.dev}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  rolePermissionsBoundary: "arn:aws:iam::#{AWS::AccountId}:policy/oslokommune/oslokommune-boundary"
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ssm:GetParameter'
      Resource:
        - "arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/dataplatform/poc-policy-server/*"
  iamManagedPolicies:
    - 'arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess'
  tags:
    GIT_REV: ${git:branch}:${git:sha1}
    VERSION: ${self:custom.version}
  environment:
    GIT_REV: ${git:branch}:${git:sha1}
    STAGE: ${self:provider.stage}
    VERSION: ${self:custom.version}
    SERVICE_NAME: ${self:service}
    KEYCLOAK_REALM: api-catalog
    KEYCLOAK_SERVER: ***REMOVED***
    RESOURCE_SERVER_CLIENT_ID: poc-resource-server
    KC_ADMIN_USERNAME: ***REMOVED***

package:
  exclude:
    - '**/*'
  include:
    - dataplatform_keycloak/*.py
    - handlers/*.py

functions:
  give-access: ${file(serverless/functions/give_access.yml)}
  list-permissions: ${file(serverless/functions/list_permissions.yml)}

plugins:
  - serverless-python-requirements
  - serverless-plugin-git-variables
  - serverless-pseudo-parameters
  - serverless-es-logs
  - serverless-aws-documentation

resources:
  Description: |
    ${self:service} ${git:branch}:${git:sha1}
    ${git:message}

custom:
  version: 0.1.0
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    usePoetry: false
  esLogs:
    endpoint: ${ssm:/dataplatform/shared/logs-elasticsearch-endpoint}
    index: dataplatform-services
    filterPattern: '{ $.function_name = "*" }'
  exportGitVariables: false
  deploymentBucket:
    prod: ok-origo-dataplatform-config-prod
    dev: ok-origo-dataplatform-config-dev
  documentation:
    info:
      version: ${git:sha1}
      title: 'policy-server-poc'
      description: 'Harmless endpoints for testing policy-server-poc'
    models: ${file(serverless/models.yml)}
  keycloakArn:
    prod: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:keycloak-authorizer-prod-authenticate
    dev: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:keycloak-authorizer-dev-authenticate