---
swagger: "2.0"
info:
  version: "2020-10-28T13:05:26Z"
  title: "dev-policy-server-poc"
host: "68bxt0vz76.execute-api.eu-west-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /data-downloader/{dataset}/{version}/{edition}:
    get:
      parameters:
      - name: "dataset"
        in: "path"
        required: true
        type: "string"
      - name: "version"
        in: "path"
        required: true
        type: "string"
      - name: "edition"
        in: "path"
        required: true
        type: "string"
      responses: {}
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /data-uploader:
    post:
      description: "Creates signed url for posting to s3-prefix"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "UploadRequest"
        description: "Metadata"
        required: true
        schema:
          $ref: "#/definitions/UploadRequest"
      responses:
        200:
          description: "200 response"
        400:
          description: "400 response"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /event-stream/{dataset_id}/{version}:
    post:
      parameters:
      - name: "version"
        in: "path"
        required: true
        type: "string"
      - name: "dataset_id"
        in: "path"
        required: true
        type: "string"
      responses: {}
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /events/{dataset_id}/{version}:
    post:
      parameters:
      - name: "version"
        in: "path"
        required: true
        type: "string"
      - name: "dataset_id"
        in: "path"
        required: true
        type: "string"
      responses: {}
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /metadata/datasets:
    post:
      description: "Create a new dataset"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Dataset"
        description: "Dataset metadata"
        required: true
        schema:
          $ref: "#/definitions/Dataset"
      responses:
        201:
          description: "201 response"
          schema:
            $ref: "#/definitions/Dataset"
        400:
          description: "400 response"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /metadata/datasets/{dataset_id}:
    get:
      description: "Create a new dataset"
      produces:
      - "application/json"
      responses:
        201:
          description: "201 response"
          schema:
            $ref: "#/definitions/Dataset"
    put:
      description: "Update dataset"
      responses:
        201:
          description: "201 response"
        400:
          description: "400 response"
definitions:
  Dataset:
    type: "object"
    properties:
      dataset_id:
        type: "string"
  UploadRequest:
    type: "object"
    properties:
      dataset_id:
        type: "string"
      edition:
        type: "string"
      version:
        type: "string"
