name: Deploy Prod
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Setup local keycloak
      run: make setup-keycloak-local
    - name: Set up Python 3.11
      uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
      with:
        python-version: '3.11'
    - name: Install Python dependencies
      run: pip install tox
    - name: Test with tox
      run: tox -e py,flake8,black
    - name: Tear down local keycloak
      run: make tear-down-keycloak-local
    - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        node-version: '20.x'
    - name: Install NPM dependencies
      run: npm install
    - name: Deploy Lambda functions
      run: |
        AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_PROD }} \
        AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }} \
        ./node_modules/.bin/sls deploy -s prod
