name: Deploy Dev

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Setup local keycloak
      run: make setup-keycloak-local
    - name: Set up Python 3.11
      uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
      with:
        python-version: '3.11'
    - name: Install Python dependencies
      run: pip install tox
    - name: Test with tox
      run: tox -e py,flake8,black
    - name: Tear down local keycloak
      run: make tear-down-keycloak-local
    - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        node-version: '20.x'
    - name: Install NPM dependencies
      run: npm install
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_DEV }}:role/github-deploy
        aws-region: eu-west-1
    - name: Sts GetCallerIdentity
      run: aws sts get-caller-identity
    - name: Deploy Lambda functions
      run: ./node_modules/.bin/sls deploy -s dev
