name: PR Tests
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: setup local keycloak
      run: make setup-keycloak-local
    - name: Set up Python 3.11
      uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install tox
    - name: Test with tox
      run: tox -e py,flake8,black
    - name: Tear down local keycloak
      run: make tear-down-keycloak-local
